### PR TITLE
Updated return types to improve chaining

### PR DESCRIPTION
**Pull request by nmhub**
- After fullText(), contains() should be next, and so on
- Update return types ensures the correct order of chaining methods

### CODE REVIEW

**Comment by br14n-sol** [comment]
Hi sorry for the delay and thank you for your contribution 🙂

I tested the code locally and everything works as expected.

**Review by br14n-sol — APPROVED** [review]

**Comment by br14n-sol** [comment]
Sorry about this but could you reopen the pull request? I didn't realize that the commit you added to this one didn't follow the conventions by which actions in this repository work (changelog, publish).

**Comment by nmhub** [comment]
Ok - looking into how to do that

**Comment by br14n-sol** [comment]
The simplest way would be to do this:

1. In your local repository of this project go to the main branch and synchronize the changes.
2. While still in the main branch create a new branch and switch to it: `git switch -c chaining-2`
3. Find the commit containing the changes that have been reverted: `git log chaining`
    In this case it would be: 49a6e8519ffeabb611d6dc96e6dfaa80dae1bad7
5. Copy the changes made in the commit to the branch we are in (chaining-2): `git cherry-pick --no-commit 49a6e8519ffeabb611d6dc96e6dfaa80dae1bad7`
6. Just commit again and open a pull request

**Comment by br14n-sol** [comment]
For step 5, in the commit message I think it would be correct something like `fix(types): updated return types to improve chaining` since it is a change that improves the developer experience but does not change the final functionality, I do not know what you think about it?

**Comment by br14n-sol** [comment]
I apologize if at some point what I am trying to say is not correctly understood, English is not my main language 😅

**Pull request merged**
